#hi
name: Update Data

on:
  workflow_call:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4

      # Other steps that change files in the repository

      - name: Debug
        run: |
          echo "Current directory:"
          echo $pwd
          echo $ls

      - name: Download data & Update files
        run: |
          mkdir -p data
          curl -o data/chateaus.json -f https://birch.catenarymaps.org/getchateaus
          curl -o data/agencies.json -f https://birch.catenarymaps.org/get_agencies

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
